#pragma once

#include "utils/enums.h"

// NOLINTBEGIN(cppcoreguidelines-macro-usage)

#define DEFAULT_CPS_LOGGING_LEVEL ArduinoLogLevel::LogLevelTrace
#define DEFAULT_BLE_SERVICE BleServiceFlag::FtmsService
#define ENABLE_WEBSOCKET_MONITOR true
#define ENABLE_WEBGUI true
#define ENABLE_BLE_SERVICE true
#define DEVICE_NAME SwellSync

// Hardware settings
#define WAKEUP_SENSOR_PIN_NUMBER GPIO_NUM_25 // for Lolin D32 and Wemos D1 Mini
#define HALL_SENSOR_PIN_NUMBER GPIO_NUM_15
#define HALL_ON_SWITCH_PIN_NUMBER GPIO_NUM_22

//#define SENSOR_PIN_NUMBER GPIO_NUM_10 // for Wemos C3 Mini

#define IMPULSES_PER_REVOLUTION 4
//#define FLYWHEEL_INERTIA 0.125 //WW
#define FLYWHEEL_INERTIA 0.113 //JH
#define LED_BLINK_FREQUENCY 1000
#define SPROCKET_RADIUS 1.50
#define CONCEPT_2_MAGIC_NUMBER 2.5

// Sensor signal filter settings
#define ROTATION_DEBOUNCE_TIME_MIN 7
#define ROWING_STOPPED_THRESHOLD_PERIOD 7000

// Drag factor filter settings
#define GOODNESS_OF_FIT_THRESHOLD 0.85
#define MAX_DRAG_FACTOR_RECOVERY_PERIOD 6000
#define LOWER_DRAG_FACTOR_THRESHOLD 75
#define UPPER_DRAG_FACTOR_THRESHOLD 250
#define DRAG_COEFFICIENTS_ARRAY_LENGTH 1

// Stroke phase detection filter settings
#define MINIMUM_POWERED_TORQUE 0
#define MINIMUM_DRAG_TORQUE 0
#define STROKE_DETECTION_TYPE STROKE_DETECTION_SLOPE
#define MINIMUM_RECOVERY_SLOPE_MARGIN 0.0000122 // Only relevant if STROKE_DETECTION_TYPE is either BOTH or TORQUE
#define MINIMUM_RECOVERY_SLOPE 0.00           // Only relevant if STROKE_DETECTION_TYPE is either BOTH or SLOPE
#define STROKE_DEBOUNCE_TIME 200
#define IMPULSE_DATA_ARRAY_LENGTH 8
// #define FLOATING_POINT_PRECISION PRECISION_DOUBLE

// Network settings
#define PORT 80

// Device power management settings
#define BATTERY_PIN_NUMBER GPIO_NUM_35 // for Lolin D32

//#define BATTERY_PIN_NUMBER GPIO_NUM_36 // for Wemos D1 Mini

//#define BATTERY_READ_MV 1 // for Wemos D1 Mini
#define BATTERY_MVOLTAGE_MIN 2800
#define BATTERY_MVOLTAGE_MAX 3134

//#define BATTERY_PIN_NUMBER  // for Wemos C3 Mini
#define VOLTAGE_DIVIDER_RATIO 2
#define BATTERY_VOLTAGE_MIN 3.3
#define BATTERY_VOLTAGE_MAX 4.00
#define BATTERY_LEVEL_ARRAY_LENGTH 5
#define INITIAL_BATTERY_LEVEL_MEASUREMENT_COUNT 10
#define BATTERY_MEASUREMENT_FREQUENCY 10
#define DEEP_SLEEP_TIMEOUT 4

#define SUPPORT_WAKEUP 1

#define SIMULATE_STROKES 0

#define ELEGANTOTA_USE_ASYNC_WEBSERVER 1
#define ELEGANTOTA_DEBUG 1
#define UPDATE_DEBUG 1
#define ESP32 1

#define HW_VERSION 1.0
#define FW_VERSION 1.0

// NOLINTEND(cppcoreguidelines-macro-usage)